<?php
/**
 * SiteMode social template
 *
 * @category   Hatmeige
 * @package    Hatmeige_SiteMode
 * @author     Hatmeige <hatmeige@gmail.com>
 */
?>
<div class="row">
    <div class="col-sm-12 social">
        <a href="<?php echo $this->socialLink('facebook'); ?>" target="_blank"><span class="icon"><i class="fab fa-facebook-square fa-3x facebook"></i></span></a>
        <a href="<?php echo $this->socialLink('twitter'); ?>" target="_blank"><span class="icon"><i class="fab fa-twitter-square fa-3x twitter"></i></span></a>
        <a href="<?php echo $this->socialLink('instagram'); ?>" target="_blank"><span class="icon"><i class="fab fa-instagram fa-3x instagram"></i></span></a>
    </div>
</div>